### ISSUE TITLE
dapp.knownorigin.io Couldn't Find My Account

### ISSUE THREAD

**Issue by realrufans** [knownorigin/known-origin-web3-marketplace#139]
# Expected behavior
I expected it to recognized my account after signing in with MetaMask.

# Actual behavior
It doesn't load my account or give any notification that i have successfully signed in with MetaMask. it gives this error message ```Looks like we can't see your account, have you logged into your wallet yet? 🔐```

# How to reproduce
head to dapp.knownorigin.io  to Login with MetaMask
Reload the or click on account.

# Gif

https://img.esteem.ws/qvx9s0ohko.gif

**Comment by jamesmorgan** [comment]
Thanks for raising this, and sorry its not connecting? Could you tell me what browser and its version and what version of metamask you are using?

Cheers

James

**Comment by realrufans** [comment]
Same thing after updating my Chrome browser.
https://www.youtube.com/watch?v=x0CdNNNIgMM&feature=youtu.be

I was on Chrome V 72.0.3626.121 (Official Build) (64-bit) but I have updated it to Version 73.0.3683.86 (Official Build) (64-bit). Then for MetaMask, I'm on V6.2.2.

**Comment by jamesmorgan** [comment]
Hi again @realrufans - I have been looking into this today and added a some debug output and deployed it to our test site.

If you visit this site its out test site but I have enabled a new flag - if you append a parameter `__debug` it should then allow you to see a virtual console - green button, bottom right - do you see any errors in your console?

e.g. https://beta-known-origin-io.firebaseapp.com/account?__debug

Maybe we can carry on this talk on telegram or email?

Cheers

James

**Comment by realrufans** [comment]
Telegram: @realrufans
