### ISSUE TITLE
Can not load the website normally after log in MetaMask  

### ISSUE THREAD

**Issue by wuxichuma** [knownorigin/known-origin-web3-marketplace#148]
**Describe the bug**
Can not load the website normally after log in MetaMask 

**To Reproduce**
After log in with my MetaMask account, and granting right to the website, that but happens.

**Screenshots**

![image](https://user-images.githubusercontent.com/29559459/57963964-68e1e700-795f-11e9-89b2-a6339d9695db.png)

![image](https://user-images.githubusercontent.com/29559459/57963968-74351280-795f-11e9-9aa9-46c57d09f1ea.png)

![image](https://user-images.githubusercontent.com/29559459/57963971-8911a600-795f-11e9-9e59-da2f75516857.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version latest

**Comment by wuxichuma** [comment]
![image](https://user-images.githubusercontent.com/29559459/57963985-c5450680-795f-11e9-858d-6c401263006c.png)

My account can be displayed successfully.

**Comment by jamesmorgan** [comment]
Only just seen this @wuxichuma sorry - I have made some changes to the account loading process recently - maybe this is fixed with my latest changes?

**Comment by jamesmorgan** [comment]
Closing as not sure if this is still an issue
